language: python

dist: xenial

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce
      - qemu-user-static

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

branches:
  only:
    - master
    - develop
    - /^hotfix/.*$/
    - /^v\d+\.\d+\.\d+(-S*)?$/

jobs:
  include:
    ## amd64
    - stage: build images
      name: amd64
      before_install: .travis/setup_emulation.sh
      script:
        - set -e
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/bootstrap_image.sh -u project8 -r dragonfly -t v1.19.4-amd64 -a amd64 -i admx/dragonfly-extended:`echo ${TRAVIS_BRANCH} | tr / _`
    ## arm32v7
    - stage: build images
      name: arm32v7
      before_install: .travis/setup_emulation.sh
      script:
        - set -e
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/bootstrap_image.sh -u project8 -r dragonfly -t v1.19.4-arm -a arm7 -i admx/dragonfly-extended:`echo ${TRAVIS_BRANCH} | tr / _`
    ## arm64v8
    - stage: build images
     name: arm64v8
     before_install: .travis/setup_emulation.sh
     script:
       - set -e
       - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
       - .travis/bootstrap_image.sh -u project8 -r dragonfly -t v1.19.0 -a arm8 -i admx/dragonfly-extended:`echo ${TRAVIS_BRANCH} | tr / _`

    ## build the manifest
    - stage: assemble manifest
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/build_manifest.sh -a arm -a amd64 -n admx/dragonfly-extended:`echo ${TRAVIS_BRANCH} | tr / _`
